api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    
    path('<int:how_many>/', views.get_saved_notifications, name='saved_notifications'),
    
    #to implement/improve
    #path('new/', views.NotiList.as_view()),
    #path('new/<int:pk>/', views.NotiDetail.as_view()),
    
    path('', views.new_notifications_view, name='notifications'),#scraps new notifications (i.e. first 1 page and compare to previously stored)
]

code_share/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    #path('', views.home, name='home'),
    
    path('v0/', views.snippet_page, name='home'),
    path('<int:page>/', views.snippet_page, name="get_snippets"),
    path('code/', views.home, name='toy_post'),
    path('edit/<str:parent_id>/', views.edit_code, name='edit_code_by_parent_id'),
    path('edit/', views.edit_code, name='edit_code'), # for some strange reasons edit is sending to code/edit
    path('code/code/', views.post_detail, name='post_detail'),
    #path('<str:uuid>/', views.code_by_uuid, name='code_by_uuid'),
    path('code/<str:uuid>/', views.code_by_uuid, name='code_by_uuid'),
    path('mail/', views.sendMail, name='send_mail'),
    path('.well-known/acme-challenge/3ufveaLc9JnIgj9y5-f9jrhb8Vgz2fSAFTbKguBTMYk', views.ssl_cert, name = 'ssl_cert'),

    path('add_star/', views.add_star, name='add_star'),
    path('search', views.search_code, name='search_code'),
    path('delete', views.delete_code, name='delete_code'),

    #path('imagepage/', views.imagepage, name='imagepage'),
    path('refresh/', views.refresh, name='refresh'),

    path('', views.create_container, name = 'home2'),
    path('<int:page>/<str:is_new_container>/', views.create_container, name = 'home2'),
    path('', views.create_container, name = 'create_container'),
    path('new_container', views.new_container, name = 'new_container'),
    # path(r'(?P<page>\d+)/(?P<is_new_container>\w+)$', views.create_container, name = 'home2'),
    # path(r'(?P<page>\d+)/(?P<is_new_container>\w+)$/', views.create_container, name = 'home2'),
    path('upload/', views.upload_files, name='upload_files'),
    path('success/', views.upload_success, name='success'),
    path('containers/', views.container_list, name='container-list'),
    path('editor/', views.editor, name='editor'),
    
    path('um/', views.upload_multiple_files, name='upload_multiple_files'),
    path('uc/', views.upload_one_code, name='upload_one_code'),
    
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
#source: https://github.com/divanov11/photo-album-app

#/person
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    
    #path('random/', views.random_person, name='random'),
    path('', views.ImagesHome, name='images_home'),
]

ioee/urls.py
# urls.py
"""ioee URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
#from code_share.views import ssl_cert
from api import views as api

from django.contrib.auth import views as auth_views
from . import views


from django.contrib.sitemaps.views import sitemap
from .sitemaps import EachCodeViewSitemap, CodeHomePageViewSitemap

sitemaps = {
    'cods_collection': CodeHomePageViewSitemap,
    'each_codes': EachCodeViewSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    # path('code/', include('code_share.urls')),
    
    path('images/', include('images.urls')),
    #path('community/', include('community.urls')),
    
    # for login and logout
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}),
    path('ioe_overflow/', include('ioe_overflow.urls')),
    path('pdf/', include('pdf_engine.urls')),
    path('pdf', include('pdf_engine.urls')),
    path('', include('code_share.urls')),

    path('community/', include('person.urls')),
]

code_share/forms.py
from .models import Code    # , Comment
from django import forms
from django.db import models

class CodeForm(forms.ModelForm):
    class Meta:
        model = Code
        fields = ('title', 'code', 'author', 'email', 'tags')
        #fields = ('name', 'email', 'body')

'''
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
'''

class EmailForm(forms.Form):
    recipient = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)


# from .models import File


class UploadFileForm(forms.Form):
    author = forms.CharField(max_length=25, required=False)
    title = forms.CharField(max_length=255, required=False)
    description = forms.CharField(max_length=500, widget=forms.Textarea, required=False)
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        # model = File
        fields = ['author', 'title', 'description', 'file_field']

# ------------------
# New form Format
# ------------------
from django import forms
from .models import Container, Files, Codes

class ContainerForm(forms.Form):
    title = forms.CharField(max_length=255)
    author = forms.CharField(max_length=255, required=False)
    email = forms.EmailField()
    tags = forms.CharField(max_length=255, required=False)
    is_private = forms.BooleanField(required=False)
    class Meta:
        model = Container
        fields = ['title', 'author', 'email', 'tags', 'is_private']

# class FilesForm(forms.ModelForm):
#     class Meta:
#         model = Files
#         fields = ['link', 'type']
class FilesForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        # model = File
        fields = ['file_field']
class FilesForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        # model = File
        fields = ['file_field']
    
    # def clean(self):
    #     cleaned_data = super().clean()
    #     file_field = cleaned_data.get('file_field')

    #     if not file_field:
    #         body = cleaned_data.get('body')
    #         print(f'body is :{body}')
    #         if not body:
    #             raise forms.ValidationError("1.Either the 'file_field' or the 'body' field must be provided.")

    #     return cleaned_data
class CodesForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea, max_length=1000, required=False)
    class Meta:
        # model = Codes
        fields = ['body']
    
# * check if body and file are empty

code_share/views.py
import math
from .models import Code, Branch, Photo, Codes
from .forms import CodeForm
from django.shortcuts import render, get_object_or_404
from django.core.mail import BadHeaderError #, send_mail
from django.urls import reverse


from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect, JsonResponse
from .forms import EmailForm
from django.conf import settings
from django.core import serializers
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch

import requests, os
from requests.structures import CaseInsensitiveDict
from .functions import DriveFunctions
from .serializers import ContainerSerializer
from django.db.models import Prefetch
from django.utils import timezone

#source: https://stackoverflow.com/questions/18264304/get-clients-real-ip-address-on-heroku#answer-18517550
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


@login_required(login_url='login')
def addPhoto(request):
    user = request.user

    categories = user.category_set.all()

    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images')

        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(
                user=user,
                name=data['category_new'])
        else:
            category = None

        for image in images:
            photo = Photo.objects.create(
                category=category,
                description=data['description'],
                image=image,
            )

        return redirect('gallery')

    context = {'categories': categories}
    return render(request, 'photos/add.html', context)

#@login_required
def home(request):
    #print('\n\nIp: ' + str(get_client_ip(request)) +'\n\n')
    template_name = 'code_share/home.html'
    #post = get_object_or_404(Post, slug=slug)

    new_code = None
    # code posted
    if request.method == 'POST':
        code_form = CodeForm(data=request.POST)
        if code_form.is_valid():
            code = request.POST.get("code", None)
            title = request.POST.get("title", None)
            author = request.POST.get("author", None)
            email = request.POST.get("email", None)
            tags = request.POST.get("tags", None).split(' ')
            
            private_code = request.POST.get("private_code", None)
            private_code = (False, True) [private_code=="on"]       #To hide the private code
            
            
            print(private_code)
            print(code, title, email)
            # Create code object but don't save to database yet
            new_code = Code.objects.create(
                code=code, email=email, title=title, tags=tags, author=author, stars=0, private_code=private_code, author_ip = get_client_ip(request))
            # Assign the current post to the code
            #new_code.post = post
            # Save the code to the database
            new_code.save()
            
            # Saving images if given
            images = request.FILES.getlist('images')
            for image in images:
                photo = Photo.objects.create(
                    #category = category,
                    title = title,
                    image=image,
                    parent_code = new_code
            )
            
            print('\n\n {} \n\n'.format(str(new_code.id)))
            if email.strip() != '':
                sent = send_mail_please(recipient=[
                                 email], subject="code", message=format_email_message_body(str(new_code.id)))
                if sent:
                    # valid email true
                    new_code.valid_email=True
                    new_code.save()
    # else:
    code_form = CodeForm()
    codes = Code.objects.filter(private_code=False).order_by('-created_on')
    data = serializers.serialize('json', codes)
    branches = Branch.objects.filter(private_code=False).order_by('-created_on')
    branches = serializers.serialize('json', branches)
    images = Photo.objects.all()
    #data = serializers.serialize('json', {'codes': codes, 'new_code': new_code, 'code_form': code_form} )

    return render(request, 'code_share/home.html', {'data': data, codes: new_code, 'code_form': code_form, 'branches':branches, 'search_term':''})

def search_code(request):
    if request.method == "GET":
        # get the nick name from the client side.
        search_term = request.GET.get("search_query", None)
        print(search_term)
        codes_list = Code.objects.annotate(
        search=SearchVector('title','author','email','tags', 'code')).filter(search=search_term)
        
        codes=[]
        for code in codes_list:
            codes.append(code)
        codes = serializers.serialize('json', codes, )
        print(codes)
        #print('peoples_list:\n\n'+str(peoples_list))
        branches = Branch.objects.filter(private_code=False).order_by('-created_on')
        branches = serializers.serialize('json', branches)
    else:
        print('\nfucking request not get\n')
        branches=''
    return render(request, 'code_share/home.html', {'data': codes, 'new_code': [], 'code_form': CodeForm(), 'branches':branches, 'search_term':search_term})
    #  {'people':people}, status = 200)



#@login_required
def snippet_page(request, page=1):
    print(f"page:{page}")
    #print('\n\nIp: ' + str(get_client_ip(request)) +'\n\n')
    template_name = 'code_share/home.html'
    #post = get_object_or_404(Post, slug=slug)

    new_code = None
    # code posted
    if request.method == 'POST': 
        code_form = CodeForm(data=request.POST)
        if code_form.is_valid():
            code = request.POST.get("code", None)
            title = request.POST.get("title", None)
            author = request.POST.get("author", None)
            email = request.POST.get("email", None)
            tags = request.POST.get("tags", None).split(' ')
            
            private_code = request.POST.get("private_code", None)
            private_code = (False, True) [private_code=="on"]       #To hide the private code
            
            
            print(private_code)
            print(code, title, email)
            # Create code object but don't save to database yet
            new_code = Code.objects.create(
                code=code, email=email, title=title, tags=tags, author=author, stars=0, private_code=private_code, author_ip = get_client_ip(request))
            # Assign the current post to the code
            #new_code.post = post
            
            # check if it exists in the database
            if not Code.objects.filter(code=code, email=email, title=title, tags=tags, author=author, private_code=private_code).exists():
                message = {'message':'Saved successfully', 'status':'success'}
                # Save the code to the database
                new_code.save()
            else:
                message = {'message':'Code already exists', 'status':'danger'}
            
            # Saving images if given
            images = request.FILES.getlist('images')
            for image in images:
                photo = Photo.objects.create(
                    #category = category,
                    title = title,
                    image=image,
                    parent_code = new_code
            )
            
            print('\n\n {} \n\n'.format(str(new_code.id)))
            if email.strip() != '':
                send_mail_please(recipient=[
                                 email], subject="code", message=format_email_message_body(str(new_code.id)))
    # else:
    # message = {'message':'Teest message', 'status':'success'}
    message = None
    max_pages = math.ceil(Code.objects.all().count()/10)
    code_form = CodeForm()
    codes = Code.objects.filter(private_code=False).order_by('-created_on')[(page-1)*10:(page)*10]
    data = serializers.serialize('json', codes)
    branches = Branch.objects.filter(private_code=False).order_by('-created_on')
    branches = serializers.serialize('json', branches)
    images = Photo.objects.all()
    #data = serializers.serialize('json', {'codes': codes, 'new_code': new_code, 'code_form': code_form} )

    return render(request, 'code_share/home.html', {'data': data, 'codes': new_code, 'code_form': code_form, 'branches':branches, 'search_term':'', 'max_pages' : max_pages, 'message': message})


def format_email_message_body(uuid):
    message = "Here is your code: https://ioee.herokuapp.com/code/{}/\n\n".format(
        str(uuid))
    #message += "anyone who has this link has right to delete it?"
    #message += "You can delete this code by verifying this email"
    return(message)


def send_mail_please(recipient, subject="uuid", message='hello World', name=''):
    # prevents header injection attack?
    if '\n' in recipient:
        raise BadHeaderError

    headers = CaseInsensitiveDict()
    headers["x-trustifi-key"] = os.environ.get('TRUSTIFI_KEY')
    headers["x-trustifi-secret"] = os.environ.get('TRUSTIFI_SECRET')
    headers["Content-Type"] = "application/json"

    url='https://be.trustifi.com/api/i/v1/email'
    print(f'\'{recipient}\', \'{subject}\', \'{message}\'')
    # data = """    {{
    # "recipients": [{{"email": "aanandaprashadgiri@gmail.com", "name": "aananda"}}],
    # "title": "conversation",
    # "html": "some message"
    # }}   """.format(recipient, name, subject, message)
    
    data = {
    "recipients": [{"email": recipient, "name": name}],
    "title": subject,
    "html": message}
    
    print(data)

code_share/templates/code_share/base.html
    <head>
        <title>Anonymous code sharing</title>
    </head>


    <!-- For bootstrap-5 -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<!-- For jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<div class="card border-info mb-3 mx-auto mt-3" style="max-width: 30rem;">
  <div class="card-header"><h1><b> {{ new_code.author | linebreaks  }}{{ new_code.title }}?</h1></b></div>
  <div class="card-body">
    <h5 class="card-title p-2"><b>This is the app/bot that does attendance for you in fuse-classroom so that you don't become disqualified for exams for being absent in class.</b></h5>
    <p class="card-text"><b><h2></h2><br>
    
    
    </p>
    <div class="card-footer bg-transparent border-success"> <h2 class='p-2 m-2'><b>How does it Work? </b></h2>
     well, it logs in with your login information periodically ( in every 30 minutes ), click join_class if any live classes are being conducted and close the page which triggers fuse-classroom to record your attendance.
     </div>
    <div class="card-footer bg-transparent border-success mt-5 m-2 p-3"><br>  Logs/records/attendance: <a href="https://discord.com/api/oauth2/authorize?client_id=862191340355715093&permissions=2148002880&scope=bot"> Discord_Bot </a> </div>
  </div>
</div><br><br>

<hr class='mt-3'>
<h1><b><center><p class="mt-2 mx-auto d-block" id="register_message"> Register: </p></center></b></h1>
<hr>




<form action='' method='POST' id="register_form">
  {% csrf_token %}
  
  
    <div class="mx-auto d-block form-floating ms-2 me-2 col-md-4">
    <input type="text" class="form-control" id="username" name="username" placeholder="user" name="username" required>
    <label for="floatingInput" class="text-secondary"> Username (same as fuse-classroom's) </label>
    <div id="usernameHelper" class="form-text" style="color:green;display:none;"> Please enter the username above. </div>
  </div>
  <br>
  
    <div class="form-floating col-md-4 ms-2 me-2 ">
    <input type="password" class="form-control" id="password" name="password" placeholder="user" name="password" required>
    <label for="floatingInput" class="text-secondary"> Password (same as fuse-classroom's) </label>
    <div id="passwordHelper" class="form-text" style="color:green;display:none;"> Please enter the password above. </div>
  </div><br>
  
  </div>
</div>


    <div class="form-floating col-md-4 ms-2 me-2 ">
    <input type="text" class="form-control" id="login_url" name="login_url" placeholder="user" name="password" value="https://sagarmatha.student.fuseclassroom.com/login/" required>
    <label for="floatingInput" class="text-secondary"> Fuse classroom login URL </label>
    <div id="urlHelper" class="form-text" style="color:green;display:none;"> Fuse-classroom login url. </div>
  </div><br><br>
  
  </div>
</div>

  
</form>


<div class="col-12">
  <button class="btn btn-primary mt-4 ms-2" id="register_btn" onClick="Register();"> Submit </button>
</div><br><br>











<!-- ---------------- code for copy to clipboard ------------------------ -->
<script>
function copyCode(){
  selectText('discord_code');
  document.execCommand("copy");
  
  btn = document.getElementById("copy_btn");
  btn.textContent='copied';
  
  document.getElementById("copy_btn").title = 'copied';
  //var tooltip = document.getElementById("myTooltip");
  //tooltip.innerHTML = "Copied: "
  
}
function selectText(node) {
    node = document.getElempasentById(node);

    if (document.body.createTextRange) {
        const range = document.body.createTextRange();
        range.moveToElementText(node);
        range.select();
    } else if (window.getSelection) {
        const selection = window.getSelection();
        const range = document.createRange();
        range.selectNodeContents(node);
        selection.removeAllRanges();
        selection.addRange(range);
    } else {
        console.warn("Could not select text in node: Unsupported browser.");
    }
}


function outFunc() {
  var tooltip = document.getElementById("myTooltip");
  tooltip.innerHTML = "Copy to clipboard";
  console.log('hover_mode');
}
</script>

<div id="Successful_registration" style="display:none">
  <h3><b>Please copy this command :"
  
  <span id="discord_code">
  </span>"
  
  <button onclick="copyCode();" id="copy_btn" class="btn-success mx-auto d-block rounded" onmouseout="outFunc();" data-toggle="tooltip" data-placement="top" title="Copy" style="background:'green'"> copy_command </button><br>

  
   and paste it in <a href="https://discord.gg/yK6xCfvwff"> Discord_Bot </a>
  </h3></b>
  

code_share/templates/code_share/dropzone.html
<div class="dropzone" id="file-dropzone">
    <p>(optional) Drag and drop files here</p>
    <!-- <label for="file-input" class="btn btn-primary">Choose File</label> -->
    <input name="file_field" id="id_file_field" name="file_field" type="file" multiple="">
    <div class="preview-container" id="file-preview-container"></div>
</div>
<div class="preview-container" id="file-preview-container"></div>
<div class="progress" id="upload-progress"></div>
<label id="unselect-files" class="btn btn-danger mt-3" onclick="document.getElementById('id_file_field').value=null;">Unselect All</label>

code_share/templates/code_share/image.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="./style.css"/>

    <title>SS - Online Exam Soln</title>
  </head>
  

  <body>
    <div class="container-fluid-lg">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Online Exam Soln</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="/"
                  >All</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link " href="/postquestion">Post</a>
              </li> 
                    <li class="nav-item">
                <a class="nav-link active" href="/imagepage">ScreenShot</a>
              </li>
            </ul>
       <form class="d-flex" enctype="multipart/form-data" action="/imagepage"  method="POST">
             {% csrf_token %}  

          <input type="file" required multiple name="uploadedfile" id="uploadedfile" style="display:none;"/>
          <label for="uploadedfile"style="margin-right: 20px;padding: 5px; color: white; border: solid 2px;background: green;">Choose image</label>
          <button class="btn btn-primary" name="uploadimage" id="uploadimage" type="submit">Upload</button>
                    

            </form>
          </div>
        </div>
      </nav>
    </div>
    <div class="container-lg my-4">

{% for rs in image %}
    <div class="card my-2 shadow-sm mx-auto" >
      <div class="card-body my-2 d-flex align-items-center justify-content-between ">
        <div class="card_left " style="width: 100%">
        <img src="{{rs.image.url}}" width="100%" height="auto">
        </div>
      </div>
    </div>
{% endfor %}
   
    </div>


    
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
    crossorigin="anonymous"
  ></script>
</html>

code_share/templates/code_share/mail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>Send Email</title>
  </head>
  <body>
    {% if messageSent %}
    <div class="container">
      <h3><strong>Email successfully sent</strong></h3>
      <p>Your message was successfully sent to {{ form.cleaned_data.to }}</p>
    </div>
    {% else %}
    <div class="container">
      <h3><strong>Send E-mail</strong></h3>

      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <br />
        <div class="text-center">
          <input
            type="submit"
            class="btn btn-secondary"
            style="width: 100%"
            value="Send e-mail"
          />
        </div>
      </form>
    </div>
    {% endif %}
  </body>
</html>

code_share/templates/code_share/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ codes.count }} code</h2>

        {% for code in codes %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ code.name }}
            <span class=" text-muted font-weight-normal">
              {{ code.created_on }}
            </span>
          </p>
          {{ code.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_code %}
        <div class="alert alert-success" role="alert">
          Your code is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ code_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

code_share/templates/code_share/template.html
<form method="post" style="margin-top: 1.3em;" action="/code/">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>



        <br><h3>new_codes:</h3><br>
        {% if new_comment %}
        <!--<div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>-->

        
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ new_comment.author }}
            <span class=" text-muted font-weight-normal">
              {{ new_comment.created_on }}
            </span>
          </p>
          {{ new_comment.comment | linebreaks }}
        </div>
        
          {%endif%}
        
        


          <br><h3>old_codes:</h3><br>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.author }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.comment | linebreaks }}
        </div>
        {% endfor %}